wf_name: test-vk-swif-nersc

jobs:
- slurm:
    project: m3792
    walltime: 00:30:00
    queue: debug
    constraint: cpu
    nodes: "1"
  site:
    name: perlmutter
    home_dir: /global/homes/j/jlabtsai/swif
    globus_endpoint: 63e2f6ac-a46f-4853-b518-e6e33859e860
    login_user: jlabtsai
    login_host_addr: perlmutter
  job:
    vk_node_name: vk-swif-nersc
    cmd_file: /global/homes/j/jlabtsai/vk-cmd.sh