kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Values.Pod.name}}"
data:
  stress.sh: |
    #!/bin/bash
    /workspaces/virtual-kubelet-cmd/test-run/svc/sample_exporter/sample_exporter -port {{ .Values.Service.targetPort }}