apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Pod.name}}
  labels:
    app: {{ .Values.Pod.name}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.Pod.name}}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: {{ .Values.Service.targetPort }}
